backend:
  Image:
    Name: kuberlab/digitalsuits-shopify-app
    Tag: latest
  baseUrl: https://extension-shopify.veriken.net
  db:
    host: host
    port: 5432
    user: postgres
    password: passwd
    dbname: shopify
  dns:
    - extension-shopify.veriken.net
  replicas: 1
  envVars:
    - name: SHOPIFY_API_KEY
      value: ""
    - name: SHOPIFY_API_SECRET
      value: "e"
    - name: SCOPES
      value: "read_products,write_products,read_orders,write_orders,read_inventory,write_inventory,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"
    - name: SHOP
      value: ""
    - name: VERIKEN_API_URL
      value: "https://testnet.veriken.net/api/v1"
