apiVersion: v1
data:
  admins.json: {{ .Values.credentials.admins }}
  recaptcha.json: {{ .Values.credentials.recaptcha }}
  s3.json: {{ .Values.credentials.s3 }}
  smtp.json: {{ .Values.credentials.smtp }}
  webrtc.json: {{ .Values.credentials.webrtc }}
  shopify.json: {{ .Values.credentials.shopify }}
  stripe.json: {{ .Values.credentials.stripe }}
kind: Secret
metadata:
  name: nft-planet-credentials
type: Opaque
